export const GET_BALANCE_START = "GET_BALANCE_START";
export const GET_BALANCE_SUCCESS = "GET_BALANCE_SUCCESS";
export const GET_BALANCE_ERROR = "GET_BALANCE_ERROR";
export const SET_BALANCES = "SET_BALANCES";
export const REMOVE_BALANCE = "REMOVE_BALANCE";
